db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
python-build:
  image: python:2.7
  links: [db]
  command: ["./ci/build.sh"]
  volumes: [".:/code"]
  working_dir: "/code"
python-lint:
  image: python:2.7
  command: ["./ci/lint.sh"]
  volumes: [".:/code"]
  working_dir: "/code"
